services:
  - type: web
    name: bookmark-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bookmark-api.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bookmark-api.settings
